version: "3"

networks:
  treafiktests_proxy:
    external:
      name: treafiktests_proxy

services:
  jametpl_static:
    build: .
    image: registry.gitlab.com/zymen/jametpl:latest
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:jamet.pl
      - traefik.docker.network=treafiktests_proxy
    ports:
      - 80:80
#    volumes:
#      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
      - treafiktests_proxy
