name: Deploy to dokku

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Deploy to dokku 
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          dokku-host: 64.227.120.171
          app-name: jametpl
          ssh-private-key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
